In [2]:
! pip install chembl_webresource_client

Requirement already satisfied: chembl_webresource_client in c:\users\monsruti devi\appdata\local\programs\python\python313\lib\site-packages (0.10.9)
Requirement already satisfied: urllib3 in c:\users\monsruti devi\appdata\local\programs\python\python313\lib\site-packages (from chembl_webresource_client) (2.5.0)
Requirement already satisfied: requests>=2.18.4 in c:\users\monsruti devi\appdata\local\programs\python\python313\lib\site-packages (from chembl_webresource_client) (2.32.4)
Requirement already satisfied: requests-cache~=1.2 in c:\users\monsruti devi\appdata\local\programs\python\python313\lib\site-packages (from chembl_webresource_client) (1.2.1)
Requirement already satisfied: easydict in c:\users\monsruti devi\appdata\local\programs\python\python313\lib\site-packages (from chembl_webresource_client) (1.13)
Requirement already satisfied: attrs>=21.2 in c:\users\monsruti devi\appdata\local\programs\python\python313\lib\site-packages (from requests-cache~=1.2->chembl_webresource_client) (25.4.0)
Requirement already satisfied: cattrs>=22.2 in c:\users\monsruti devi\appdata\local\programs\python\python313\lib\site-packages (from requests-cache~=1.2->chembl_webresource_client) (25.3.0)
Requirement already satisfied: platformdirs>=2.5 in c:\users\monsruti devi\appdata\local\programs\python\python313\lib\site-packages (from requests-cache~=1.2->chembl_webresource_client) (4.3.8)
Requirement already satisfied: url-normalize>=1.4 in c:\users\monsruti devi\appdata\local\programs\python\python313\lib\site-packages (from requests-cache~=1.2->chembl_webresource_client) (2.2.1)
Requirement already satisfied: typing-extensions>=4.14.0 in c:\users\monsruti devi\appdata\local\programs\python\python313\lib\site-packages (from cattrs>=22.2->requests-cache~=1.2->chembl_webresource_client) (4.14.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\monsruti devi\appdata\local\programs\python\python313\lib\site-packages (from requests>=2.18.4->chembl_webresource_client) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\monsruti devi\appdata\local\programs\python\python313\lib\site-packages (from requests>=2.18.4->chembl_webresource_client) (3.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\monsruti devi\appdata\local\programs\python\python313\lib\site-packages (from requests>=2.18.4->chembl_webresource_client) (2025.6.15)

In [5]:
import pandas as pd
from chembl_webresource_client.new_client import new_client

In [6]:
target = new_client.target
target_query = target.search("coronavirus")
targets = pd.DataFrame.from_dict(target_query)
targets

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Coronavirus,Coronavirus,17.0,False,CHEMBL613732,[],ORGANISM,11119
1,[],Feline coronavirus,Feline coronavirus,15.0,False,CHEMBL612744,[],ORGANISM,12663
2,[],Murine coronavirus,Murine coronavirus,15.0,False,CHEMBL5209664,[],ORGANISM,694005
3,[],Canine coronavirus,Canine coronavirus,15.0,False,CHEMBL5291668,[],ORGANISM,11153
4,[],Bovine coronavirus,Bovine coronavirus,15.0,False,CHEMBL6066646,[],ORGANISM,11128
5,[],Human coronavirus 229E,Human coronavirus 229E,13.0,False,CHEMBL613837,[],ORGANISM,11137
6,[],Human coronavirus OC43,Human coronavirus OC43,13.0,False,CHEMBL5209665,[],ORGANISM,31631
7,[],Middle East respiratory syndrome-related coron...,Middle East respiratory syndrome-related coron...,10.0,False,CHEMBL4296578,[],ORGANISM,1335626
8,[],Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,5.0,False,CHEMBL3927,"[{'accession': 'P0C6U8', 'component_descriptio...",SINGLE PROTEIN,694009
9,[],Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1ab,4.0,False,CHEMBL5118,"[{'accession': 'P0C6X7', 'component_descriptio...",SINGLE PROTEIN,694009
10,[],Severe acute respiratory syndrome coronavirus 2,Replicase polyprotein 1ab,3.0,False,CHEMBL4523582,"[{'accession': 'P0DTD1', 'component_descriptio...",SINGLE PROTEIN,2697049
11,[],Severe acute respiratory syndrome coronavirus 2,Protein cereblon-SARS-Cov-2 polyprotein,3.0,False,CHEMBL6067603,"[{'accession': 'Q96SW2', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,2697049
12,[],Severe acute respiratory syndrome coronavirus 2,von Hippel-Lindau disease tumor suppressor-SAR...,3.0,False,CHEMBL6067604,"[{'accession': 'P40337', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,2697049

here we are storing the new client in target
then searching for target
from the target we are making data frame using dict
printing targets to get it

In [ ]:
selected_target = targets.target_chembl_id[8] #in df targets target chemble id column was chosen and 8th index was taken
selected_target

'CHEMBL3927'

In [ ]:
activity = new_client.activity
res = activity.filter(target_chembl_id = selected_target).filter(standard_type= "IC50")  # standard type ic50= how much of drug needed to inhibit 50% of the protein

in activity variable were storing activity of that target
in the activity were searching for the selected targets id whose standard type is IC50

In [ ]:
df= pd.DataFrame.from_dict(res)
df

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,1480935,[],CHEMBL829584,In vitro inhibitory concentration against SARS...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,uM,UO_0000065,None,7.2
1,None,None,1480936,[],CHEMBL829584,In vitro inhibitory concentration against SARS...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,uM,UO_0000065,None,9.4
2,None,None,1481061,[],CHEMBL830868,In vitro inhibitory concentration against SARS...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,uM,UO_0000065,None,13.5
3,None,None,1481065,[],CHEMBL829584,In vitro inhibitory concentration against SARS...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,uM,UO_0000065,None,13.11
4,None,None,1481066,[],CHEMBL829584,In vitro inhibitory concentration against SARS...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,uM,UO_0000065,None,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256,"{'action_type': 'INHIBITOR', 'description': 'N...",None,25992021,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5550822,Inhibition of SARS-CoV-1 main protease using D...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,nM,UO_0000065,None,52.0
257,"{'action_type': 'INHIBITOR', 'description': 'N...",None,25992022,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5550822,Inhibition of SARS-CoV-1 main protease using D...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,nM,UO_0000065,None,30.0
258,"{'action_type': 'INHIBITOR', 'description': 'N...",None,25992023,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5550822,Inhibition of SARS-CoV-1 main protease using D...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,nM,UO_0000065,None,14.0
259,"{'action_type': 'INHIBITOR', 'description': 'N...",None,25992024,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5550822,Inhibition of SARS-CoV-1 main protease using D...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,nM,UO_0000065,None,48.0
260,"{'action_type': 'INHIBITOR', 'description': 'N...",None,25992025,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5550822,Inhibition of SARS-CoV-1 main protease using D...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,nM,UO_0000065,None,20.0

:

In [16]:
df.standard_type.unique()

array(['IC50'], dtype=object)

we only want 1 bioactivity unit because mixture will cause uniformity

In [17]:
df.to_csv("Bioactivity_data.csv", index = False)